name: bet_me_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  blur: ^3.1.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^3.0.2
  country_picker: ^2.0.15
  cupertino_icons: ^1.0.5
  dart_extensions: ^2.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  expandable_text: ^2.3.0
  firebase_core: ^2.1.1
  firebase_dynamic_links: ^5.0.3
  flutter_bloc: ^8.0.1
  flutter_contacts: ^1.1.5
  flutter_facebook_auth: ^5.0.0+2
  flutter_native_timezone: ^2.0.0
#  flutter_phoenix: ^1.0.0
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  media_info: ^0.12.0+1
  permission_handler: ^10.2.0
  phone_number: ^1.0.0
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  #  sign_in_with_apple: ^3.3.0
  timezone: ^0.9.0
  top_snackbar_flutter: ^2.1.1
  video_player: ^2.4.5
  better_player: ^0.0.83
  visibility_detector: ^0.3.3
  url_launcher: ^6.1.5
  bloc_concurrency: ^0.2.0
  external_app_launcher: ^3.0.0
  flutter_braintree: ^2.3.1
  camera: ^0.10.0+4
  percent_indicator: ^4.2.2
  photo_manager: ^2.4.1
  flutter_local_notifications: ^12.0.3
  firebase_messaging: ^14.1.0
  timeago: ^3.3.0
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.6
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3
  rename: ^2.0.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Medium.ttf
        - asset: assets/fonts/Fredoka-Light.ttf
          weight: 300
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700